import { app } from 'electron';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';

import { store } from '../settings';

const COOKIE_BROWSER_ALLOWLIST = new Set([
    'brave',
    'chrome',
    'chromium',
    'edge',
    'firefox',
    'opera',
    'safari',
    'vivaldi',
    'whale',
]);

const COOKIE_BROWSER_AUTO_ATTEMPTS = ['edge', 'chrome', 'firefox', 'brave', 'chromium'];

const normalizeCookieBrowser = (value?: string) => {
    const browser = (value || '').trim().toLowerCase();
    if (!COOKIE_BROWSER_ALLOWLIST.has(browser)) return '';
    return browser;
};

const writeSessionCookiesFile = (cookieHeader: string) => {
    const dir = path.join(app.getPath('userData'), 'yt-cookies');
    mkdirSync(dir, { recursive: true });
    const filePath = path.join(dir, 'youtube-music-session.txt');
    const lines = ['# Netscape HTTP Cookie File', '# Generated by Roofy Music'];

    for (const part of cookieHeader.split(';')) {
        const trimmed = part.trim();
        const separator = trimmed.indexOf('=');
        if (separator <= 0) continue;
        const name = trimmed.slice(0, separator).trim();
        const value = trimmed.slice(separator + 1).trim();
        if (!name) continue;
        lines.push(`.youtube.com\tTRUE\t/\tTRUE\t0\t${name}\t${value}`);
        lines.push(`.google.com\tTRUE\t/\tTRUE\t0\t${name}\t${value}`);
    }

    writeFileSync(filePath, `${lines.join('\n')}\n`, 'utf8');
    return filePath;
};

export const getYtDlpCookieArgs = (sessionCookieHeader?: string) => {
    const cookiesFilePath = store.get('roofy.cookiesFilePath') as string | undefined;
    if (cookiesFilePath && existsSync(cookiesFilePath)) {
        return ['--cookies', cookiesFilePath];
    }

    const configuredBrowser = normalizeCookieBrowser(
        store.get('roofy.cookieBrowser') as string | undefined,
    );
    if (configuredBrowser) {
        return ['--cookies-from-browser', configuredBrowser];
    }

    if (sessionCookieHeader) {
        return ['--cookies', writeSessionCookiesFile(sessionCookieHeader)];
    }

    const rawBrowser = (store.get('roofy.cookieBrowser') as string | undefined) || '';
    if (rawBrowser.trim().toLowerCase() === 'auto') {
        return ['--cookies-from-browser', COOKIE_BROWSER_AUTO_ATTEMPTS[0]];
    }

    return [];
};
