import retroOverridesCss from './retro_overrides.css?inline';

import { AppThemeConfiguration } from '/@/shared/themes/app-theme-types';

export const retroMonochrome: AppThemeConfiguration = {
    app: {
        'content-max-width': '1800px',
        'overlay-header': 'none',
        'overlay-subheader': 'none',
        'root-font-size': '14px',
        'scrollbar-handle-active-background': 'rgba(255,255,255,0.42)',
        'scrollbar-handle-background': 'rgba(255,255,255,0.28)',
        'scrollbar-handle-border-radius': '0',
        'scrollbar-handle-hover-background': 'rgba(255,255,255,0.42)',
        'scrollbar-size': '10px',
        'scrollbar-track-active-background': '#070707',
        'scrollbar-track-background': '#070707',
        'scrollbar-track-border-radius': '0',
        'scrollbar-track-hover-background': '#070707',
    },
    colors: {
        background: '#050505',
        'background-alternate': '#070707',
        black: '#000000',
        foreground: '#f2f2f2',
        'foreground-muted': '#a6a6a6',
        primary: '#f2f2f2',
        'state-error': '#707070',
        'state-info': '#a6a6a6',
        'state-success': '#f2f2f2',
        'state-warning': '#707070',
        surface: '#0b0b0b',
        'surface-foreground': '#f2f2f2',
        white: '#f2f2f2',
    },
    mantineOverride: {
        defaultRadius: 0,
        fontFamily: '"IBM Plex Mono", "Courier New", monospace',
        headings: {
            fontFamily: '"IBM Plex Mono", "Courier New", monospace',
            fontWeight: '700',
            sizes: {
                h1: { fontSize: '2rem', fontWeight: '900', lineHeight: '1.2' },
                h2: { fontSize: '1.75rem', fontWeight: '900', lineHeight: '1.2' },
                h3: { fontSize: '1.5rem', fontWeight: '900', lineHeight: '1.2' },
                h4: { fontSize: '1.25rem', fontWeight: '900', lineHeight: '1.2' },
                h5: { fontSize: '1rem', fontWeight: '900', lineHeight: '1.2' },
                h6: { fontSize: '0.875rem', fontWeight: '900', lineHeight: '1.2' },
            },
        },
        primaryColor: 'dark',
        primaryShade: { dark: 5, light: 9 },
        radius: {
            lg: '0px',
            md: '0px',
            sm: '0px',
            xl: '0px',
            xs: '0px',
        },
        shadows: {
            lg: 'none',
            md: 'none',
            sm: 'none',
            xl: 'none',
            xs: 'none',
            xxl: 'none',
        },
    },
    mode: 'dark',
    stylesheets: [retroOverridesCss],
};
